# Generated by Django 5.2.4 on 2025-09-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
