# Generated by Django 5.2.5 on 2025-09-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0005_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file_path',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(null=True, upload_to='attachments/'),
        ),
    ]
