# Generated by Django 5.2.5 on 2025-09-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0006_remove_attachment_file_path_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
