# Generated by Django 5.2.5 on 2025-09-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0008_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='login_registration_app.case'),
        ),
    ]
